# Numpyの基礎

In [1]:
import numpy as np

In [18]:
# 型を調べる
data = np.array([3, 1, 2])
print(data.dtype)

# 次元
print(data.ndim)

# 要素数
print(data.size)

#ソート:もとのリストを変更するので注意
data.sort()
print(data)

# 最大最小
print(data.min())
print(data.max())

# 合計
print(data.sum())

# 積み上げ
print(data.cumsum())

# 積み上げ割合
print(data.cumsum() / data.sum())

int64
1
3
[1 2 3]
1
3
6
[1 3 6]
[0.16666667 0.5        1.        ]


In [22]:
## 乱数

# シード値
np.random.seed(0)

# 正規分布の乱数を10個発生
rnd_data = np.random.randn(10)
print(rnd_data)

[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799 -0.97727788
  0.95008842 -0.15135721 -0.10321885  0.4105985 ]


In [27]:
## 抽出
data = np.array([9, 2, 3, 4, 10, 6, 7, 8, 1, 5])

# 復元抽出
print(np.random.choice(data, 10))

#非復元抽出
print(np.random.choice(data, 10, replace=False))

[10 10  4 10 10  1 10  4  8  6]
[ 3 10  7  1  4  8  5  2  9  6]


In [46]:
# 行列

array1 = np.arange(9).reshape(3, 3)
print(array1, '\n')

# 1行目
print('1行目', array1[0, :], '\n')

# 1列目
print('1列目', array1[:, 0], '\n')

# 行列の演算
array2 = np.arange(9, 18).reshape(3, 3)
print(array2, '\n')

#内積
print(np.dot(array1, array2), '\n')

#ゼロ行列
print(np.zeros((3,2), dtype=np.int64), '\n')

# 1行列
print(np.ones((3,2), dtype=np.float64), '\n')

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

1行目 [0 1 2] 

1列目 [0 3 6] 

[[ 9 10 11]
 [12 13 14]
 [15 16 17]] 

[[ 42  45  48]
 [150 162 174]
 [258 279 300]] 

[[0 0]
 [0 0]
 [0 0]] 

[[1. 1.]
 [1. 1.]
 [1. 1.]] 



# Pandasの基礎

In [1]:
import pandas as pd

## series

In [6]:
data_list = range(0, 100, 10)
print(list(data_list))

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]


In [7]:
sample_pandas_data = pd.Series(data_list)
print(sample_pandas_data)

0     0
1    10
2    20
3    30
4    40
5    50
6    60
7    70
8    80
9    90
dtype: int64


In [9]:
#インデックスを付ける

sample_pandas_index_data = pd.Series(
  data_list,
  index=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'])
print(sample_pandas_index_data)

a     0
b    10
c    20
d    30
e    40
f    50
g    60
h    70
i    80
j    90
dtype: int64


## DataFrame

In [13]:
attri_data1 = {'ID':range(100, 105),
              'City':['Tokyo', 'Osaka', 'Nagano', 'Nagoya', 'Okinawa'],
              'Birth_year':[1990, 1989, 1992, 1997, 1982],
              'Name':['AAA', 'BBB', 'CCC', 'DDD', 'EEE']}

attri_data_frame1 = pd.DataFrame(attri_data1)
print(attri_data_frame1)

    ID     City  Birth_year Name
0  100    Tokyo        1990  AAA
1  101    Osaka        1989  BBB
2  102   Nagano        1992  CCC
3  103   Nagoya        1997  DDD
4  104  Okinawa        1982  EEE


In [17]:
attri_data_frame_index1 = pd.DataFrame(attri_data1, index=['a', 'b', 'c', 'd', 'e'])
print(attri_data_frame_index1)

    ID     City  Birth_year Name
a  100    Tokyo        1990  AAA
b  101    Osaka        1989  BBB
c  102   Nagano        1992  CCC
d  103   Nagoya        1997  DDD
e  104  Okinawa        1982  EEE
